http:
  read_timeout: 50s
  write_timeout: 50s
pg_conf:
	# conn := `host=localhost user=role1 dbname=ahuigo sslmode=disable password=`
  host: localhost
  user: role1
  password:
  dbname: ahuigo
  sslmode: disable
  port: 5432
  max_idle_conns: 10